osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 1 3 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 2 3 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 3 3 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 4 3 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 5 3 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 6 3 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 7 3 3"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 8 3 3"'

osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 9 2 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 10 2 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 11 2 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 12 2 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 13 2 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 14 2 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 15 2 3"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode2.rb 16 2 3"'
