osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 1 L 3"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 2 L 3"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 3 L 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 4 L 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 5 L 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 6 L 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 7 L 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 8 L 0"'

osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 9 F 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 10 F 0"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 11 F 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 12 F 1"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 13 F 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 14 F 2"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 15 F 3"'
osascript -e 'tell application "Terminal" to do script "./Documents/HTW/AVA/ueb02/GameNode4.rb 16 F 3"'